export const inlineTokenTypes = {
  attributes: "inlineAttributes",
  attributesMarker: "inlineAttributesMarker",
  attribute: "inlineAttribute",
  attributeId: "inlineAttributeId",
  attributeIdMarker: "inlineAttributeIdMarker",
  attributeIdValue: "inlineAttributeIdValue",
  attributeClass: "inlineAttributeClass",
  attributeClassMarker: "inlineAttributeClassMarker",
  attributeClassValue: "inlineAttributeClassValue",
  attributeName: "inlineAttributeName",
  attributeInitializerMarker: "inlineAttributeInitializerMarker",
  attributeValueLiteral: "inlineAttributeValueLiteral",
  attributeValue: "inlineAttributeValue",
  attributeValueMarker: "inlineAttributeValueMarker",
  attributeValueData: "inlineAttributeValueData",
} as const;

export const blockTokenTypes = {
  attributes: "blockAttributes",
  attributesMarker: "blockAttributesMarker",
  attribute: "blockAttribute",
  attributeId: "blockAttributeId",
  attributeIdMarker: "blockAttributeIdMarker",
  attributeIdValue: "blockAttributeIdValue",
  attributeClass: "blockAttributeClass",
  attributeClassMarker: "blockAttributeClassMarker",
  attributeClassValue: "blockAttributeClassValue",
  attributeName: "blockAttributeName",
  attributeInitializerMarker: "blockAttributeInitializerMarker",
  attributeValueLiteral: "blockAttributeValueLiteral",
  attributeValue: "blockAttributeValue",
  attributeValueMarker: "blockAttributeValueMarker",
  attributeValueData: "blockAttributeValueData",
} as const;
